name: Build nuget package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      SDK: 17.5
      SRC_FOLDER: .
      PROJ_NAME: MBProgressHUD.xcodeproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        
        
        
        
      - name: Build MBProgressHUD Framework
        run: |
          xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
            -target "MBProgressHUD Framework" \


      - name: Upload .xcframework as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: xcframework
          compression-level: '1'
          path:  ${{ env.SRC_FOLDER }}/*.xcframework
          
      - name: restore workload
        working-directory: ./dotnet-binding
        run: dotnet workload restore

      - name: Build .NET binding project
        working-directory: ./dotnet-binding
        run: dotnet build -c Release MBProgressHUD-dotnet.csproj

      - name: Pack NuGet
        working-directory: ./dotnet-binding
        run: dotnet pack -c Release MBProgressHUD-dotnet.csproj

      - name: Upload .nupkg as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nuget-package
          compression-level: '0'
          path: ${{ env.SRC_FOLDER }}/dotnet-binding/bin/Release/*.nupkg
