name: Build nuget package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      SDK: 17.5
      SRC_FOLDER: .
      PROJ_NAME: MBProgressHUD.xcodeproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build SDWebImage for simulator
        run: |
          xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
            -target "MBProgressHUD Static Library" \
            -sdk iphonesimulator${{ env.SDK }} \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            EXCLUDED_ARCHS="arm64"
