name: Build nuget package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      SDK: 17.5
      SRC_FOLDER: .
      PROJ_NAME: MBProgressHUD.xcodeproj
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        
      - name: Build MBProgressHUD for simulator
        run: |
          xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
            -target "MBProgressHUD Static Library" \
            -sdk iphonesimulator${{ env.SDK }} \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            EXCLUDED_ARCHS="arm64"

      - name: Build MBProgressHUD for device
        run: |
          xcodebuild -project ${{ env.SRC_FOLDER }}/${{ env.PROJ_NAME }} \
            -target "MBProgressHUD Static Library" \
            -sdk iphoneos${{ env.SDK }} \
            IPHONEOS_DEPLOYMENT_TARGET=12.0
          
      - name: Create universal lib with lipo
        run: |
          lipo -create \
            ${{ env.SRC_FOLDER }}/build/Release-iphoneos/libMBProgressHUD.a \
            ${{ env.SRC_FOLDER }}/build/Release-iphonesimulator/libMBProgressHUD.a \
            -output ./libMBProgressHUD.a
          lipo -info ./libMBProgressHUD.a
          
      - name: restore workload
        run: dotnet workload restore

      - name: Build .NET binding project
        run: dotnet build -c Release MBProgressHUD-dotnet.csproj

      - name: Pack NuGet
        run: dotnet pack -c Release MBProgressHUD-dotnet.csproj

      - name: Upload .nupkg as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nuget-package
          compression-level: '0'
          path:
            /Users/runner/work/SDWebImage-dotnet/MBProgressHUD-dotnet/bin/Release/*.nupkg  
